name: CI

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          wget --no-verbose https://github.com/aergoio/aergo/releases/download/v2.2.10/aergo-2.2.10.linux.tar.gz
          tar zxvf aergo-2.2.10.linux.tar.gz
          sudo cp aergo/2.2.10/bin/brick /usr/local/bin
          ./test/run_tests
